name: Static analysis
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    name: Analyze Dart
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603
        - name: Install dependencies
          working-directory: feeder
          run: dart pub get
        - name: Analyze project source
          run: dart analyze
          working-directory: feeder